#!/bin/bash

read -p "First string: " str1

while read -n 1 c;
do
        str1+=($c);
done <<< "$1"

readarray -td '' sorting1 < <(printf '%s\0' "${str1[@]}" | sort -z -u)

read -p "Second string: " str2

while read -n 1 c;
do
        str2+=($c);
done <<< "$2"

readarray -td '' sorting2 < <(printf '%s\0' "${str2[@]}" | sort -z -u)

for((i=0; i<${#sorting1[@]}; i++));
do
        list+=(${sorting1[$i]});
done

for((i=0; i<${#sorting2[@]}; i++));
do
        list+=(${sorting2[$i]});
done

readarray -td '' sorted < <(printf '%s\0' "${list[@]}" | sort -z -u)

for ((i=0; i<${#sorted[@]}; i++));
do
        echo -n ${sorted[$i]};
done

echo

exit 0
