#!/bin/bash

read -p "Length of romb: " length

if ! [[ $length =~ ^[0-9]+$ ]]; then
 echo "Number is incorrect"
 exit 1
fi

#first side

let num=$(($length-1))

for ((i=0; i<$length; i++)); do
  for ((j=0; j<$(($length-1)); j++)); do
    echo -n " "
  done
  for ((j=0;j<$num;j++)); do
    echo -n "* "
  done
echo ""

num=$(($num+1))
done

#second side
for ((i=0;i<=$(($length-1));i++)); do
  for ((j=0;j<$(($length-$num));j++)); do
    echo -n " "
  done
  for ((j=0;j<num;j++)); do
    echo -n "* "
  done
echo ""
num=$(($num-1))
done
exit 0
