#!/bin/bash

read -p "Length of romb: " length
if ! [[ $length =~ ^[0-9]+$ ]]; then
 echo "Number is incorrect"
 exit 1
fi

#first side

for ((i=1; i<=(($length-1)); i++)); do
  for ((j=1; j<=$length; j++)); do
      if (($(($length-$i)) < $j)); then
          echo -n " *"
      else
          echo -n " "
      fi
  done
  echo ""
done

#second side
for ((i=1; i<=$length; i++)); do
  for ((j=0; j<=$length; j++)); do
      if (($(($length-$i)) >= $(($length-$j)) )); then
          echo -n "* "
      else
          echo -n " "
      fi
  done
  echo ""
done 
exit 0
