#!/bin/bash

read -p "Enter: " let
index=0
for char in $let;
do
  arr[$index]=$char
  index=$(($index+1))
done

if [ $let ];
then
  echo "z"
  exit 0
fi

length=${#arr[@]}
sum=0

for (( i = 0; i < $length; i++));
do
  a=$(printf "%d\n" "'${arr[$i]}")
  sum=$(($sum+$a))
done

sum=$((($sum % 96) + 96))
if(( sum > 122 ));
then
  sum=$(($sum-26))
fi

echo $(printf "\x$(printf %x $sum)")

exit 0
